/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AbilityType = { 'transformation' : null } |
  { 'control' : null } |
  { 'summon' : null } |
  { 'area_attack' : null };
export type AvatarClass = { 'navigator' : null } |
  { 'doctor' : null } |
  { 'cook' : null } |
  { 'sniper' : null } |
  { 'swordsman' : null };
export interface ChatMessage {
  'content' : string,
  'sender' : bigint,
  'islandId' : [] | [bigint],
  'timestamp' : Time,
}
export interface CombatResult {
  'winnerId' : bigint,
  'loserId' : bigint,
  'timestamp' : Time,
  'bountyGained' : bigint,
}
export interface Crew {
  'id' : bigint,
  'islandControl' : [] | [bigint],
  'name' : string,
  'bountyTotal' : bigint,
  'memberIds' : Array<bigint>,
  'captainId' : bigint,
}
export interface DevilFruit {
  'id' : bigint,
  'element' : Element,
  'name' : string,
  'description' : string,
  'abilityType' : AbilityType,
  'rarity' : ItemRarity,
}
export type Element = { 'ice' : null } |
  { 'metal' : null } |
  { 'shadow' : null } |
  { 'fire' : null } |
  { 'wind' : null } |
  { 'gravity' : null } |
  { 'lightning' : null };
export interface InventoryItem {
  'statBonus' : bigint,
  'name' : string,
  'itemType' : ItemType,
  'rarity' : ItemRarity,
}
export interface Island {
  'id' : bigint,
  'name' : string,
  'islandType' : IslandType,
  'description' : string,
  'controlledBy' : [] | [bigint],
}
export type IslandType = { 'port' : null } |
  { 'town' : null } |
  { 'treasure' : null } |
  { 'forest' : null };
export type ItemRarity = { 'epic' : null } |
  { 'legendary' : null } |
  { 'rare' : null } |
  { 'common' : null };
export type ItemType = { 'equipment' : null } |
  { 'sword' : null } |
  { 'treasure' : null };
export interface NPC {
  'name' : string,
  'role' : NPCRole,
  'island' : bigint,
  'dialogue' : Array<string>,
}
export type NPCRole = { 'boss' : null } |
  { 'questgiver' : null } |
  { 'trainer' : null };
export interface PlayerProfile {
  'id' : bigint,
  'xp' : bigint,
  'principal' : Principal,
  'characterName' : string,
  'inventory' : Array<InventoryItem>,
  'isOnline' : boolean,
  'currentIsland' : bigint,
  'bounty' : bigint,
  'level' : bigint,
  'avatarClass' : AvatarClass,
  'stats' : PlayerStats,
  'devilFruit' : [] | [DevilFruit],
  'position' : Position,
  'lastSeen' : Time,
}
export interface PlayerStats {
  'stamina' : bigint,
  'haki' : bigint,
  'speed' : bigint,
  'strength' : bigint,
  'defense' : bigint,
}
export interface Position { 'x' : bigint, 'z' : bigint }
export interface Quest {
  'id' : bigint,
  'reward' : QuestReward,
  'completionCondition' : string,
  'name' : string,
  'description' : string,
}
export interface QuestReward { 'xp' : bigint, 'bounty' : bigint }
export type Time = bigint;
export interface UserProfile {
  'characterName' : string,
  'playerId' : [] | [bigint],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addIsland' : ActorMethod<[string, IslandType, string], undefined>,
  'addNPC' : ActorMethod<[string, NPCRole, bigint, Array<string>], undefined>,
  'addQuest' : ActorMethod<[string, string, QuestReward, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'claimIsland' : ActorMethod<[bigint, bigint], undefined>,
  'completeQuest' : ActorMethod<[bigint], undefined>,
  'createCrew' : ActorMethod<[string], bigint>,
  'createPlayer' : ActorMethod<[string, AvatarClass], PlayerProfile>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCombatResults' : ActorMethod<[], Array<CombatResult>>,
  'getCrews' : ActorMethod<[], Array<Crew>>,
  'getGlobalChat' : ActorMethod<[], Array<ChatMessage>>,
  'getIslandChat' : ActorMethod<[bigint], Array<ChatMessage>>,
  'getIslands' : ActorMethod<[], Array<Island>>,
  'getMyPlayerProfile' : ActorMethod<[], [] | [PlayerProfile]>,
  'getNPCs' : ActorMethod<[], Array<NPC>>,
  'getOnlinePlayers' : ActorMethod<[], Array<PlayerProfile>>,
  'getPlayerProfileId' : ActorMethod<[bigint], PlayerProfile>,
  'getQuests' : ActorMethod<[], Array<Quest>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'joinCrew' : ActorMethod<[bigint], undefined>,
  'leaveCrew' : ActorMethod<[bigint], undefined>,
  'logCombatResult' : ActorMethod<[bigint, bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendGlobalMessage' : ActorMethod<[string], undefined>,
  'sendIslandMessage' : ActorMethod<[bigint, string], undefined>,
  'updatePlayerIsland' : ActorMethod<[bigint], undefined>,
  'updatePlayerPosition' : ActorMethod<[bigint, bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];