/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const IslandType = IDL.Variant({
  'port' : IDL.Null,
  'town' : IDL.Null,
  'treasure' : IDL.Null,
  'forest' : IDL.Null,
});
export const NPCRole = IDL.Variant({
  'boss' : IDL.Null,
  'questgiver' : IDL.Null,
  'trainer' : IDL.Null,
});
export const QuestReward = IDL.Record({ 'xp' : IDL.Nat, 'bounty' : IDL.Nat });
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AvatarClass = IDL.Variant({
  'navigator' : IDL.Null,
  'doctor' : IDL.Null,
  'cook' : IDL.Null,
  'sniper' : IDL.Null,
  'swordsman' : IDL.Null,
});
export const ItemType = IDL.Variant({
  'equipment' : IDL.Null,
  'sword' : IDL.Null,
  'treasure' : IDL.Null,
});
export const ItemRarity = IDL.Variant({
  'epic' : IDL.Null,
  'legendary' : IDL.Null,
  'rare' : IDL.Null,
  'common' : IDL.Null,
});
export const InventoryItem = IDL.Record({
  'statBonus' : IDL.Nat,
  'name' : IDL.Text,
  'itemType' : ItemType,
  'rarity' : ItemRarity,
});
export const PlayerStats = IDL.Record({
  'stamina' : IDL.Nat,
  'haki' : IDL.Nat,
  'speed' : IDL.Nat,
  'strength' : IDL.Nat,
  'defense' : IDL.Nat,
});
export const Element = IDL.Variant({
  'ice' : IDL.Null,
  'metal' : IDL.Null,
  'shadow' : IDL.Null,
  'fire' : IDL.Null,
  'wind' : IDL.Null,
  'gravity' : IDL.Null,
  'lightning' : IDL.Null,
});
export const AbilityType = IDL.Variant({
  'transformation' : IDL.Null,
  'control' : IDL.Null,
  'summon' : IDL.Null,
  'area_attack' : IDL.Null,
});
export const DevilFruit = IDL.Record({
  'id' : IDL.Nat,
  'element' : Element,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'abilityType' : AbilityType,
  'rarity' : ItemRarity,
});
export const Position = IDL.Record({ 'x' : IDL.Int, 'z' : IDL.Int });
export const Time = IDL.Int;
export const PlayerProfile = IDL.Record({
  'id' : IDL.Nat,
  'xp' : IDL.Nat,
  'principal' : IDL.Principal,
  'characterName' : IDL.Text,
  'inventory' : IDL.Vec(InventoryItem),
  'isOnline' : IDL.Bool,
  'currentIsland' : IDL.Nat,
  'bounty' : IDL.Nat,
  'level' : IDL.Nat,
  'avatarClass' : AvatarClass,
  'stats' : PlayerStats,
  'devilFruit' : IDL.Opt(DevilFruit),
  'position' : Position,
  'lastSeen' : Time,
});
export const UserProfile = IDL.Record({
  'characterName' : IDL.Text,
  'playerId' : IDL.Opt(IDL.Nat),
});
export const CombatResult = IDL.Record({
  'winnerId' : IDL.Nat,
  'loserId' : IDL.Nat,
  'timestamp' : Time,
  'bountyGained' : IDL.Nat,
});
export const Crew = IDL.Record({
  'id' : IDL.Nat,
  'islandControl' : IDL.Opt(IDL.Nat),
  'name' : IDL.Text,
  'bountyTotal' : IDL.Nat,
  'memberIds' : IDL.Vec(IDL.Nat),
  'captainId' : IDL.Nat,
});
export const ChatMessage = IDL.Record({
  'content' : IDL.Text,
  'sender' : IDL.Nat,
  'islandId' : IDL.Opt(IDL.Nat),
  'timestamp' : Time,
});
export const Island = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'islandType' : IslandType,
  'description' : IDL.Text,
  'controlledBy' : IDL.Opt(IDL.Nat),
});
export const NPC = IDL.Record({
  'name' : IDL.Text,
  'role' : NPCRole,
  'island' : IDL.Nat,
  'dialogue' : IDL.Vec(IDL.Text),
});
export const Quest = IDL.Record({
  'id' : IDL.Nat,
  'reward' : QuestReward,
  'completionCondition' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addIsland' : IDL.Func([IDL.Text, IslandType, IDL.Text], [], []),
  'addNPC' : IDL.Func([IDL.Text, NPCRole, IDL.Nat, IDL.Vec(IDL.Text)], [], []),
  'addQuest' : IDL.Func([IDL.Text, IDL.Text, QuestReward, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'claimIsland' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'completeQuest' : IDL.Func([IDL.Nat], [], []),
  'createCrew' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'createPlayer' : IDL.Func([IDL.Text, AvatarClass], [PlayerProfile], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCombatResults' : IDL.Func([], [IDL.Vec(CombatResult)], ['query']),
  'getCrews' : IDL.Func([], [IDL.Vec(Crew)], ['query']),
  'getGlobalChat' : IDL.Func([], [IDL.Vec(ChatMessage)], ['query']),
  'getIslandChat' : IDL.Func([IDL.Nat], [IDL.Vec(ChatMessage)], ['query']),
  'getIslands' : IDL.Func([], [IDL.Vec(Island)], ['query']),
  'getMyPlayerProfile' : IDL.Func([], [IDL.Opt(PlayerProfile)], ['query']),
  'getNPCs' : IDL.Func([], [IDL.Vec(NPC)], ['query']),
  'getOnlinePlayers' : IDL.Func([], [IDL.Vec(PlayerProfile)], ['query']),
  'getPlayerProfileId' : IDL.Func([IDL.Nat], [PlayerProfile], ['query']),
  'getQuests' : IDL.Func([], [IDL.Vec(Quest)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'joinCrew' : IDL.Func([IDL.Nat], [], []),
  'leaveCrew' : IDL.Func([IDL.Nat], [], []),
  'logCombatResult' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendGlobalMessage' : IDL.Func([IDL.Text], [], []),
  'sendIslandMessage' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'updatePlayerIsland' : IDL.Func([IDL.Nat], [], []),
  'updatePlayerPosition' : IDL.Func([IDL.Int, IDL.Int], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const IslandType = IDL.Variant({
    'port' : IDL.Null,
    'town' : IDL.Null,
    'treasure' : IDL.Null,
    'forest' : IDL.Null,
  });
  const NPCRole = IDL.Variant({
    'boss' : IDL.Null,
    'questgiver' : IDL.Null,
    'trainer' : IDL.Null,
  });
  const QuestReward = IDL.Record({ 'xp' : IDL.Nat, 'bounty' : IDL.Nat });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AvatarClass = IDL.Variant({
    'navigator' : IDL.Null,
    'doctor' : IDL.Null,
    'cook' : IDL.Null,
    'sniper' : IDL.Null,
    'swordsman' : IDL.Null,
  });
  const ItemType = IDL.Variant({
    'equipment' : IDL.Null,
    'sword' : IDL.Null,
    'treasure' : IDL.Null,
  });
  const ItemRarity = IDL.Variant({
    'epic' : IDL.Null,
    'legendary' : IDL.Null,
    'rare' : IDL.Null,
    'common' : IDL.Null,
  });
  const InventoryItem = IDL.Record({
    'statBonus' : IDL.Nat,
    'name' : IDL.Text,
    'itemType' : ItemType,
    'rarity' : ItemRarity,
  });
  const PlayerStats = IDL.Record({
    'stamina' : IDL.Nat,
    'haki' : IDL.Nat,
    'speed' : IDL.Nat,
    'strength' : IDL.Nat,
    'defense' : IDL.Nat,
  });
  const Element = IDL.Variant({
    'ice' : IDL.Null,
    'metal' : IDL.Null,
    'shadow' : IDL.Null,
    'fire' : IDL.Null,
    'wind' : IDL.Null,
    'gravity' : IDL.Null,
    'lightning' : IDL.Null,
  });
  const AbilityType = IDL.Variant({
    'transformation' : IDL.Null,
    'control' : IDL.Null,
    'summon' : IDL.Null,
    'area_attack' : IDL.Null,
  });
  const DevilFruit = IDL.Record({
    'id' : IDL.Nat,
    'element' : Element,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'abilityType' : AbilityType,
    'rarity' : ItemRarity,
  });
  const Position = IDL.Record({ 'x' : IDL.Int, 'z' : IDL.Int });
  const Time = IDL.Int;
  const PlayerProfile = IDL.Record({
    'id' : IDL.Nat,
    'xp' : IDL.Nat,
    'principal' : IDL.Principal,
    'characterName' : IDL.Text,
    'inventory' : IDL.Vec(InventoryItem),
    'isOnline' : IDL.Bool,
    'currentIsland' : IDL.Nat,
    'bounty' : IDL.Nat,
    'level' : IDL.Nat,
    'avatarClass' : AvatarClass,
    'stats' : PlayerStats,
    'devilFruit' : IDL.Opt(DevilFruit),
    'position' : Position,
    'lastSeen' : Time,
  });
  const UserProfile = IDL.Record({
    'characterName' : IDL.Text,
    'playerId' : IDL.Opt(IDL.Nat),
  });
  const CombatResult = IDL.Record({
    'winnerId' : IDL.Nat,
    'loserId' : IDL.Nat,
    'timestamp' : Time,
    'bountyGained' : IDL.Nat,
  });
  const Crew = IDL.Record({
    'id' : IDL.Nat,
    'islandControl' : IDL.Opt(IDL.Nat),
    'name' : IDL.Text,
    'bountyTotal' : IDL.Nat,
    'memberIds' : IDL.Vec(IDL.Nat),
    'captainId' : IDL.Nat,
  });
  const ChatMessage = IDL.Record({
    'content' : IDL.Text,
    'sender' : IDL.Nat,
    'islandId' : IDL.Opt(IDL.Nat),
    'timestamp' : Time,
  });
  const Island = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'islandType' : IslandType,
    'description' : IDL.Text,
    'controlledBy' : IDL.Opt(IDL.Nat),
  });
  const NPC = IDL.Record({
    'name' : IDL.Text,
    'role' : NPCRole,
    'island' : IDL.Nat,
    'dialogue' : IDL.Vec(IDL.Text),
  });
  const Quest = IDL.Record({
    'id' : IDL.Nat,
    'reward' : QuestReward,
    'completionCondition' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addIsland' : IDL.Func([IDL.Text, IslandType, IDL.Text], [], []),
    'addNPC' : IDL.Func(
        [IDL.Text, NPCRole, IDL.Nat, IDL.Vec(IDL.Text)],
        [],
        [],
      ),
    'addQuest' : IDL.Func([IDL.Text, IDL.Text, QuestReward, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'claimIsland' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'completeQuest' : IDL.Func([IDL.Nat], [], []),
    'createCrew' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'createPlayer' : IDL.Func([IDL.Text, AvatarClass], [PlayerProfile], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCombatResults' : IDL.Func([], [IDL.Vec(CombatResult)], ['query']),
    'getCrews' : IDL.Func([], [IDL.Vec(Crew)], ['query']),
    'getGlobalChat' : IDL.Func([], [IDL.Vec(ChatMessage)], ['query']),
    'getIslandChat' : IDL.Func([IDL.Nat], [IDL.Vec(ChatMessage)], ['query']),
    'getIslands' : IDL.Func([], [IDL.Vec(Island)], ['query']),
    'getMyPlayerProfile' : IDL.Func([], [IDL.Opt(PlayerProfile)], ['query']),
    'getNPCs' : IDL.Func([], [IDL.Vec(NPC)], ['query']),
    'getOnlinePlayers' : IDL.Func([], [IDL.Vec(PlayerProfile)], ['query']),
    'getPlayerProfileId' : IDL.Func([IDL.Nat], [PlayerProfile], ['query']),
    'getQuests' : IDL.Func([], [IDL.Vec(Quest)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'joinCrew' : IDL.Func([IDL.Nat], [], []),
    'leaveCrew' : IDL.Func([IDL.Nat], [], []),
    'logCombatResult' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendGlobalMessage' : IDL.Func([IDL.Text], [], []),
    'sendIslandMessage' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'updatePlayerIsland' : IDL.Func([IDL.Nat], [], []),
    'updatePlayerPosition' : IDL.Func([IDL.Int, IDL.Int], [], []),
  });
};

export const init = ({ IDL }) => { return []; };