/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface PlayerStats {
    stamina: bigint;
    haki: bigint;
    speed: bigint;
    strength: bigint;
    defense: bigint;
}
export interface UserProfile {
    characterName: string;
    playerId?: bigint;
}
export type Time = bigint;
export interface PlayerProfile {
    id: bigint;
    xp: bigint;
    principal: Principal;
    characterName: string;
    inventory: Array<InventoryItem>;
    isOnline: boolean;
    currentIsland: bigint;
    bounty: bigint;
    level: bigint;
    avatarClass: AvatarClass;
    stats: PlayerStats;
    devilFruit?: DevilFruit;
    position: Position;
    lastSeen: Time;
}
export interface Island {
    id: bigint;
    name: string;
    islandType: IslandType;
    description: string;
    controlledBy?: bigint;
}
export interface Crew {
    id: bigint;
    islandControl?: bigint;
    name: string;
    bountyTotal: bigint;
    memberIds: Array<bigint>;
    captainId: bigint;
}
export interface InventoryItem {
    statBonus: bigint;
    name: string;
    itemType: ItemType;
    rarity: ItemRarity;
}
export interface Position {
    x: bigint;
    z: bigint;
}
export interface DevilFruit {
    id: bigint;
    element: Element;
    name: string;
    description: string;
    abilityType: AbilityType;
    rarity: ItemRarity;
}
export interface Quest {
    id: bigint;
    reward: QuestReward;
    completionCondition: string;
    name: string;
    description: string;
}
export interface ChatMessage {
    content: string;
    sender: bigint;
    islandId?: bigint;
    timestamp: Time;
}
export interface CombatResult {
    winnerId: bigint;
    loserId: bigint;
    timestamp: Time;
    bountyGained: bigint;
}
export interface QuestReward {
    xp: bigint;
    bounty: bigint;
}
export interface NPC {
    name: string;
    role: NPCRole;
    island: bigint;
    dialogue: Array<string>;
}
export enum AbilityType {
    transformation = "transformation",
    control = "control",
    summon = "summon",
    area_attack = "area_attack"
}
export enum AvatarClass {
    navigator = "navigator",
    doctor = "doctor",
    cook = "cook",
    sniper = "sniper",
    swordsman = "swordsman"
}
export enum Element {
    ice = "ice",
    metal = "metal",
    shadow = "shadow",
    fire = "fire",
    wind = "wind",
    gravity = "gravity",
    lightning = "lightning"
}
export enum IslandType {
    port = "port",
    town = "town",
    treasure = "treasure",
    forest = "forest"
}
export enum ItemRarity {
    epic = "epic",
    legendary = "legendary",
    rare = "rare",
    common = "common"
}
export enum ItemType {
    equipment = "equipment",
    sword = "sword",
    treasure = "treasure"
}
export enum NPCRole {
    boss = "boss",
    questgiver = "questgiver",
    trainer = "trainer"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addIsland(name: string, islandType: IslandType, description: string): Promise<void>;
    addNPC(name: string, role: NPCRole, island: bigint, dialogue: Array<string>): Promise<void>;
    addQuest(name: string, description: string, reward: QuestReward, completionCondition: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    claimIsland(crewId: bigint, islandId: bigint): Promise<void>;
    completeQuest(questId: bigint): Promise<void>;
    createCrew(name: string): Promise<bigint>;
    createPlayer(characterName: string, avatarClass: AvatarClass): Promise<PlayerProfile>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCombatResults(): Promise<Array<CombatResult>>;
    getCrews(): Promise<Array<Crew>>;
    getGlobalChat(): Promise<Array<ChatMessage>>;
    getIslandChat(islandId: bigint): Promise<Array<ChatMessage>>;
    getIslands(): Promise<Array<Island>>;
    getMyPlayerProfile(): Promise<PlayerProfile | null>;
    getNPCs(): Promise<Array<NPC>>;
    getOnlinePlayers(): Promise<Array<PlayerProfile>>;
    getPlayerProfileId(id: bigint): Promise<PlayerProfile>;
    getQuests(): Promise<Array<Quest>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    joinCrew(crewId: bigint): Promise<void>;
    leaveCrew(crewId: bigint): Promise<void>;
    logCombatResult(loserId: bigint, bountyGained: bigint): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    sendGlobalMessage(content: string): Promise<void>;
    sendIslandMessage(islandId: bigint, content: string): Promise<void>;
    updatePlayerIsland(islandId: bigint): Promise<void>;
    updatePlayerPosition(x: bigint, z: bigint): Promise<void>;
}
import type { AbilityType as _AbilityType, AvatarClass as _AvatarClass, ChatMessage as _ChatMessage, Crew as _Crew, DevilFruit as _DevilFruit, Element as _Element, InventoryItem as _InventoryItem, Island as _Island, IslandType as _IslandType, ItemRarity as _ItemRarity, ItemType as _ItemType, NPC as _NPC, NPCRole as _NPCRole, PlayerProfile as _PlayerProfile, PlayerStats as _PlayerStats, Position as _Position, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addIsland(arg0: string, arg1: IslandType, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addIsland(arg0, to_candid_IslandType_n1(this._uploadFile, this._downloadFile, arg1), arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addIsland(arg0, to_candid_IslandType_n1(this._uploadFile, this._downloadFile, arg1), arg2);
            return result;
        }
    }
    async addNPC(arg0: string, arg1: NPCRole, arg2: bigint, arg3: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addNPC(arg0, to_candid_NPCRole_n3(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addNPC(arg0, to_candid_NPCRole_n3(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
            return result;
        }
    }
    async addQuest(arg0: string, arg1: string, arg2: QuestReward, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addQuest(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addQuest(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async claimIsland(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.claimIsland(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.claimIsland(arg0, arg1);
            return result;
        }
    }
    async completeQuest(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.completeQuest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completeQuest(arg0);
            return result;
        }
    }
    async createCrew(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createCrew(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCrew(arg0);
            return result;
        }
    }
    async createPlayer(arg0: string, arg1: AvatarClass): Promise<PlayerProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.createPlayer(arg0, to_candid_AvatarClass_n7(this._uploadFile, this._downloadFile, arg1));
                return from_candid_PlayerProfile_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPlayer(arg0, to_candid_AvatarClass_n7(this._uploadFile, this._downloadFile, arg1));
            return from_candid_PlayerProfile_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCombatResults(): Promise<Array<CombatResult>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCombatResults();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCombatResults();
            return result;
        }
    }
    async getCrews(): Promise<Array<Crew>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCrews();
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCrews();
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGlobalChat(): Promise<Array<ChatMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getGlobalChat();
                return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGlobalChat();
            return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getIslandChat(arg0: bigint): Promise<Array<ChatMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getIslandChat(arg0);
                return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getIslandChat(arg0);
            return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getIslands(): Promise<Array<Island>> {
        if (this.processError) {
            try {
                const result = await this.actor.getIslands();
                return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getIslands();
            return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyPlayerProfile(): Promise<PlayerProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyPlayerProfile();
                return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyPlayerProfile();
            return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNPCs(): Promise<Array<NPC>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNPCs();
                return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNPCs();
            return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOnlinePlayers(): Promise<Array<PlayerProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOnlinePlayers();
                return from_candid_vec_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOnlinePlayers();
            return from_candid_vec_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPlayerProfileId(arg0: bigint): Promise<PlayerProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlayerProfileId(arg0);
                return from_candid_PlayerProfile_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlayerProfileId(arg0);
            return from_candid_PlayerProfile_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getQuests(): Promise<Array<Quest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuests();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuests();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async joinCrew(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.joinCrew(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.joinCrew(arg0);
            return result;
        }
    }
    async leaveCrew(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.leaveCrew(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.leaveCrew(arg0);
            return result;
        }
    }
    async logCombatResult(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.logCombatResult(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logCombatResult(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n51(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n51(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async sendGlobalMessage(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.sendGlobalMessage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendGlobalMessage(arg0);
            return result;
        }
    }
    async sendIslandMessage(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.sendIslandMessage(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendIslandMessage(arg0, arg1);
            return result;
        }
    }
    async updatePlayerIsland(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePlayerIsland(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePlayerIsland(arg0);
            return result;
        }
    }
    async updatePlayerPosition(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePlayerPosition(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePlayerPosition(arg0, arg1);
            return result;
        }
    }
}
function from_candid_AbilityType_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AbilityType): AbilityType {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid_AvatarClass_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AvatarClass): AvatarClass {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_ChatMessage_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ChatMessage): ChatMessage {
    return from_candid_record_n38(_uploadFile, _downloadFile, value);
}
function from_candid_Crew_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Crew): Crew {
    return from_candid_record_n35(_uploadFile, _downloadFile, value);
}
function from_candid_DevilFruit_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DevilFruit): DevilFruit {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_Element_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Element): Element {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_InventoryItem_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InventoryItem): InventoryItem {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_IslandType_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _IslandType): IslandType {
    return from_candid_variant_n43(_uploadFile, _downloadFile, value);
}
function from_candid_Island_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Island): Island {
    return from_candid_record_n41(_uploadFile, _downloadFile, value);
}
function from_candid_ItemRarity_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ItemRarity): ItemRarity {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_ItemType_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ItemType): ItemType {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_NPCRole_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NPCRole): NPCRole {
    return from_candid_variant_n49(_uploadFile, _downloadFile, value);
}
function from_candid_NPC_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NPC): NPC {
    return from_candid_record_n47(_uploadFile, _downloadFile, value);
}
function from_candid_PlayerProfile_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PlayerProfile): PlayerProfile {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n29(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_DevilFruit]): DevilFruit | null {
    return value.length === 0 ? null : from_candid_DevilFruit_n21(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n28(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PlayerProfile]): PlayerProfile | null {
    return value.length === 0 ? null : from_candid_PlayerProfile_n9(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    xp: bigint;
    principal: Principal;
    characterName: string;
    inventory: Array<_InventoryItem>;
    isOnline: boolean;
    currentIsland: bigint;
    bounty: bigint;
    level: bigint;
    avatarClass: _AvatarClass;
    stats: _PlayerStats;
    devilFruit: [] | [_DevilFruit];
    position: _Position;
    lastSeen: _Time;
}): {
    id: bigint;
    xp: bigint;
    principal: Principal;
    characterName: string;
    inventory: Array<InventoryItem>;
    isOnline: boolean;
    currentIsland: bigint;
    bounty: bigint;
    level: bigint;
    avatarClass: AvatarClass;
    stats: PlayerStats;
    devilFruit?: DevilFruit;
    position: Position;
    lastSeen: Time;
} {
    return {
        id: value.id,
        xp: value.xp,
        principal: value.principal,
        characterName: value.characterName,
        inventory: from_candid_vec_n11(_uploadFile, _downloadFile, value.inventory),
        isOnline: value.isOnline,
        currentIsland: value.currentIsland,
        bounty: value.bounty,
        level: value.level,
        avatarClass: from_candid_AvatarClass_n18(_uploadFile, _downloadFile, value.avatarClass),
        stats: value.stats,
        devilFruit: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.devilFruit)),
        position: value.position,
        lastSeen: value.lastSeen
    };
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    statBonus: bigint;
    name: string;
    itemType: _ItemType;
    rarity: _ItemRarity;
}): {
    statBonus: bigint;
    name: string;
    itemType: ItemType;
    rarity: ItemRarity;
} {
    return {
        statBonus: value.statBonus,
        name: value.name,
        itemType: from_candid_ItemType_n14(_uploadFile, _downloadFile, value.itemType),
        rarity: from_candid_ItemRarity_n16(_uploadFile, _downloadFile, value.rarity)
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    element: _Element;
    name: string;
    description: string;
    abilityType: _AbilityType;
    rarity: _ItemRarity;
}): {
    id: bigint;
    element: Element;
    name: string;
    description: string;
    abilityType: AbilityType;
    rarity: ItemRarity;
} {
    return {
        id: value.id,
        element: from_candid_Element_n23(_uploadFile, _downloadFile, value.element),
        name: value.name,
        description: value.description,
        abilityType: from_candid_AbilityType_n25(_uploadFile, _downloadFile, value.abilityType),
        rarity: from_candid_ItemRarity_n16(_uploadFile, _downloadFile, value.rarity)
    };
}
function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    characterName: string;
    playerId: [] | [bigint];
}): {
    characterName: string;
    playerId?: bigint;
} {
    return {
        characterName: value.characterName,
        playerId: record_opt_to_undefined(from_candid_opt_n30(_uploadFile, _downloadFile, value.playerId))
    };
}
function from_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    islandControl: [] | [bigint];
    name: string;
    bountyTotal: bigint;
    memberIds: Array<bigint>;
    captainId: bigint;
}): {
    id: bigint;
    islandControl?: bigint;
    name: string;
    bountyTotal: bigint;
    memberIds: Array<bigint>;
    captainId: bigint;
} {
    return {
        id: value.id,
        islandControl: record_opt_to_undefined(from_candid_opt_n30(_uploadFile, _downloadFile, value.islandControl)),
        name: value.name,
        bountyTotal: value.bountyTotal,
        memberIds: value.memberIds,
        captainId: value.captainId
    };
}
function from_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    content: string;
    sender: bigint;
    islandId: [] | [bigint];
    timestamp: _Time;
}): {
    content: string;
    sender: bigint;
    islandId?: bigint;
    timestamp: Time;
} {
    return {
        content: value.content,
        sender: value.sender,
        islandId: record_opt_to_undefined(from_candid_opt_n30(_uploadFile, _downloadFile, value.islandId)),
        timestamp: value.timestamp
    };
}
function from_candid_record_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    name: string;
    islandType: _IslandType;
    description: string;
    controlledBy: [] | [bigint];
}): {
    id: bigint;
    name: string;
    islandType: IslandType;
    description: string;
    controlledBy?: bigint;
} {
    return {
        id: value.id,
        name: value.name,
        islandType: from_candid_IslandType_n42(_uploadFile, _downloadFile, value.islandType),
        description: value.description,
        controlledBy: record_opt_to_undefined(from_candid_opt_n30(_uploadFile, _downloadFile, value.controlledBy))
    };
}
function from_candid_record_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    role: _NPCRole;
    island: bigint;
    dialogue: Array<string>;
}): {
    name: string;
    role: NPCRole;
    island: bigint;
    dialogue: Array<string>;
} {
    return {
        name: value.name,
        role: from_candid_NPCRole_n48(_uploadFile, _downloadFile, value.role),
        island: value.island,
        dialogue: value.dialogue
    };
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    equipment: null;
} | {
    sword: null;
} | {
    treasure: null;
}): ItemType {
    return "equipment" in value ? ItemType.equipment : "sword" in value ? ItemType.sword : "treasure" in value ? ItemType.treasure : value;
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    epic: null;
} | {
    legendary: null;
} | {
    rare: null;
} | {
    common: null;
}): ItemRarity {
    return "epic" in value ? ItemRarity.epic : "legendary" in value ? ItemRarity.legendary : "rare" in value ? ItemRarity.rare : "common" in value ? ItemRarity.common : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    navigator: null;
} | {
    doctor: null;
} | {
    cook: null;
} | {
    sniper: null;
} | {
    swordsman: null;
}): AvatarClass {
    return "navigator" in value ? AvatarClass.navigator : "doctor" in value ? AvatarClass.doctor : "cook" in value ? AvatarClass.cook : "sniper" in value ? AvatarClass.sniper : "swordsman" in value ? AvatarClass.swordsman : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ice: null;
} | {
    metal: null;
} | {
    shadow: null;
} | {
    fire: null;
} | {
    wind: null;
} | {
    gravity: null;
} | {
    lightning: null;
}): Element {
    return "ice" in value ? Element.ice : "metal" in value ? Element.metal : "shadow" in value ? Element.shadow : "fire" in value ? Element.fire : "wind" in value ? Element.wind : "gravity" in value ? Element.gravity : "lightning" in value ? Element.lightning : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    transformation: null;
} | {
    control: null;
} | {
    summon: null;
} | {
    area_attack: null;
}): AbilityType {
    return "transformation" in value ? AbilityType.transformation : "control" in value ? AbilityType.control : "summon" in value ? AbilityType.summon : "area_attack" in value ? AbilityType.area_attack : value;
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    port: null;
} | {
    town: null;
} | {
    treasure: null;
} | {
    forest: null;
}): IslandType {
    return "port" in value ? IslandType.port : "town" in value ? IslandType.town : "treasure" in value ? IslandType.treasure : "forest" in value ? IslandType.forest : value;
}
function from_candid_variant_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    boss: null;
} | {
    questgiver: null;
} | {
    trainer: null;
}): NPCRole {
    return "boss" in value ? NPCRole.boss : "questgiver" in value ? NPCRole.questgiver : "trainer" in value ? NPCRole.trainer : value;
}
function from_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_InventoryItem>): Array<InventoryItem> {
    return value.map((x)=>from_candid_InventoryItem_n12(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Crew>): Array<Crew> {
    return value.map((x)=>from_candid_Crew_n34(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ChatMessage>): Array<ChatMessage> {
    return value.map((x)=>from_candid_ChatMessage_n37(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Island>): Array<Island> {
    return value.map((x)=>from_candid_Island_n40(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_NPC>): Array<NPC> {
    return value.map((x)=>from_candid_NPC_n46(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PlayerProfile>): Array<PlayerProfile> {
    return value.map((x)=>from_candid_PlayerProfile_n9(_uploadFile, _downloadFile, x));
}
function to_candid_AvatarClass_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AvatarClass): _AvatarClass {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_IslandType_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: IslandType): _IslandType {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_NPCRole_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NPCRole): _NPCRole {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n52(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_record_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    characterName: string;
    playerId?: bigint;
}): {
    characterName: string;
    playerId: [] | [bigint];
} {
    return {
        characterName: value.characterName,
        playerId: value.playerId ? candid_some(value.playerId) : candid_none()
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: IslandType): {
    port: null;
} | {
    town: null;
} | {
    treasure: null;
} | {
    forest: null;
} {
    return value == IslandType.port ? {
        port: null
    } : value == IslandType.town ? {
        town: null
    } : value == IslandType.treasure ? {
        treasure: null
    } : value == IslandType.forest ? {
        forest: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NPCRole): {
    boss: null;
} | {
    questgiver: null;
} | {
    trainer: null;
} {
    return value == NPCRole.boss ? {
        boss: null
    } : value == NPCRole.questgiver ? {
        questgiver: null
    } : value == NPCRole.trainer ? {
        trainer: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AvatarClass): {
    navigator: null;
} | {
    doctor: null;
} | {
    cook: null;
} | {
    sniper: null;
} | {
    swordsman: null;
} {
    return value == AvatarClass.navigator ? {
        navigator: null
    } : value == AvatarClass.doctor ? {
        doctor: null
    } : value == AvatarClass.cook ? {
        cook: null
    } : value == AvatarClass.sniper ? {
        sniper: null
    } : value == AvatarClass.swordsman ? {
        swordsman: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
